site_name: My Docs
site_url: https://sitename.example
theme:
  name: material
  palette:
    scheme: default
    primary: orange
    accent: deep orange
  font:
    text: Lato
    code: Fira Code
  logo: assets/map.png
  favicon: assets/favicon.png
  features: 
    - content.code.copy
    - content.code.select
    - content.code.annotate
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
