site_name: GEOGC183 - Cartographic Representation
site_url: https://cwilmott.github.io/GEOGC183/
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: grey
  font:
    text: EB Garamond
    code: Fira Code
  icon:
    logo: octicons/code-square-24
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  favicon: octicons/code-square-24.svg
  features: 
    - content.code.copy
    - content.code.select
    - content.code.annotate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
      
